// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq31uNqG-MFzvmuZek8DpB8HwXVfIPrA0',
    appId: '1:608572692640:web:f948bd4ad775165ef311c5',
    messagingSenderId: '608572692640',
    projectId: 'gestionprojet2-49ceb',
    authDomain: 'gestionprojet2-49ceb.firebaseapp.com',
    storageBucket: 'gestionprojet2-49ceb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVCVjqMO8-c5U600u7R7c0-9KH0mhzKA',
    appId: '1:608572692640:android:ccc7cc3d298611c0f311c5',
    messagingSenderId: '608572692640',
    projectId: 'gestionprojet2-49ceb',
    storageBucket: 'gestionprojet2-49ceb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOdB4QpoAmzp5ic0r6wCm5vGHk4Gzabrc',
    appId: '1:608572692640:ios:a73b612613a18368f311c5',
    messagingSenderId: '608572692640',
    projectId: 'gestionprojet2-49ceb',
    storageBucket: 'gestionprojet2-49ceb.appspot.com',
    iosBundleId: 'com.example.gestionProjet2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOdB4QpoAmzp5ic0r6wCm5vGHk4Gzabrc',
    appId: '1:608572692640:ios:bd8d87f99d17ef64f311c5',
    messagingSenderId: '608572692640',
    projectId: 'gestionprojet2-49ceb',
    storageBucket: 'gestionprojet2-49ceb.appspot.com',
    iosBundleId: 'com.example.gestionProjet2.RunnerTests',
  );
}
